apiVersion: v1
kind: Pod
metadata: 
  name: pod-yaml-file
spec:
  volumes:
    - name: mydir
      hostPath:
        path: /home/balaji/Documents/sep_20_task/Volume/Sample_volume
        type: DirectoryOrCreate
    - name: myfile
      hostPath:
        path: /home/balaji/Documents/sep_20_task/Volume/Sample_volume/index.html
        type: FileOrCreate
  containers:
  - name: my-nginx
    image: nginx:latest
    volumeMounts:
      - mountPath: /newdatafile
        name: mydir
      - mountPath: /newdatafile/index.html
        name: myfile
    ports:
    - containerPort: 80
      protocol: TCP